version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.3
  - dependency-name: fugit
    versions:
    - 1.4.4
  - dependency-name: bootsnap
    versions:
    - 1.7.0
    - 1.7.1
    - 1.7.2
  - dependency-name: puma
    versions:
    - 5.2.1
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.2.1
  - dependency-name: whatwg-fetch
    versions:
    - 3.6.1
  - dependency-name: highcharts
    versions:
    - 9.0.0
  - dependency-name: match-sorter
    versions:
    - 6.2.0
