language: ruby

cache:
  bundler: true
  directories:
    - node_modules

before_install:
  - nvm install
  - nvm use
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

before_script:
  - RAILS_ENV=test bundle exec rails db:drop db:create
  - bundle exec rails db:test:prepare

script:
  - bundle exec rake

services:
  - postgresql

addons:
  postgresql: "10.14"
