check_brand_clusters:
  cron: "0 * * * *" # Every hour
  class: CheckBrandClusters
fetch_reviews:
  cron: "0 */6 * * *" # Every six hours
  class: FetchReviews
refresh_leaderboards:
  cron: "0 */4 * * *" # Every four hours
  class: RefreshLeaderBoards
