# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      DATABASE_URL: postgres://test:test@localhost/fountainpencompanion_test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.13.0'
    - name: Install correct Yarn version
      run: npm install yarn@1.22.10 -g
    - name: Set up Postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '12' 
        postgresql db: fountainpencompanion_test
        postgresql user: test
        postgresql password: test
        
    - name: Wait / Sleep
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '10s'
    - name: Collect Docker Logs
      uses: jwalton/gh-docker-logs@v1.0.0
    - name: Check running containers
      run: docker ps -a
    - name: Try connecting to Postgres
      run: PGPASSWORD=test psql -U test -d fountainpencompanion_test -h localhost -c "SELECT version()"
      
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: yarn install
    - name: Run tests
      run: bundle exec rake
